### ISSUE TITLE
Fix bad data

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#60]
There still are a few of errors in the data fetched from the repositories that need to be fixed.

- [x] [`tests`](https://the-algorithms.com/category/tests) get picked up
- [x] Categories [`strings`](https://the-algorithms.com/category/strings) and [`string`](https://the-algorithms.com/category/string) are almost the same
- [x] The category [`src`](https://the-algorithms.com/category/src) exists somehow
- [x] These are all the same: [`sorting`](https://the-algorithms.com/category/sorting) [`sorts`](https://the-algorithms.com/category/sorts) [`sorters`](https://the-algorithms.com/category/sorters) [`sort`](https://the-algorithms.com/category/sort)
- [x] These are also all the same: [`searching`](https://the-algorithms.com/category/searching) [`searches`](https://the-algorithms.com/category/searches) [`search`](https://the-algorithms.com/category/search)
- [x] Haskell [`specs`](https://the-algorithms.com/category/specs) get picked up
- [x] [`others`](https://the-algorithms.com/category/others) [`other`](https://the-algorithms.com/category/other) [`misc`](https://the-algorithms.com/category/misc) are the same
- [x] [`math`](https://the-algorithms.com/category/math) and [`maths`](https://the-algorithms.com/category/maths) are the same
- [x] [`hashing`](https://the-algorithms.com/category/hashing), [`hashes`](https://the-algorithms.com/category/hashes) and [`hash`](https://the-algorithms.com/category/hash) are the same
- [x] [`graph`](https://the-algorithms.com/category/graph) and [`graphs`](https://the-algorithms.com/category/graphs) are the same
- [x] [`divideconquer`](https://the-algorithms.com/category/divideconquer) and [`divideandconquer`](https://the-algorithms.com/category/divideandconquer) are the same
- [x] [`algorithmstests`](https://the-algorithms.com/category/algorithmstests) shouldn't exist
- [x] [`algorithms`](https://the-algorithms.com/category/algorithms) shouldn't be a category, instead the next tags of the algorithm

Some of them need to be fixed in the workflow that creates the `DIRECTORY.md` file directly in the seperate repositories, some can be fixed by expanding the [aliases](https://github.com/TheAlgorithms/website/blob/main/lib/aliases.js) to also include categories.

**Comment by ayaankhan98** [comment]
These errors are due to different structure of each repository. I think we should bring all repositories to a common standard.

**Comment by maltejur** [comment]
Hmm thats true but a bit difficult to do. In the meantime, we've made a more general [script](https://github.com/TheAlgorithms/scripts) that can be used to create the `DIRECTORY.md` files in the different repos via a workflow (replacing the ones that are already  there).

**Comment by maltejur** [comment]
But a more common structure would always be nice. The Python, C++ and some more repos all follow a pretty similar structure already, so I think we should take that as a reference for the other repos.

But for some repos, like the [C#](https://github.com/TheAlgorithms/C-Sharp) one, this seems like a very drastic change and I don't think the maintainers would like that.

**Comment by ayaankhan98** [comment]
> But for some repos, like the [C#](https://github.com/TheAlgorithms/C-Sharp) one, this seems like a very drastic change and I don't think the maintainers would like that.

Emm we should restructure such repositories

**Comment by ayaankhan98** [comment]
In C# tests are written separately, DS and Algorithms are also placed separately. In general, each file should have it's own test function and we are supposed to execute those tests in CI to ensure the correctness of implementation. And instead of arranging the algorithms and DS separately, we should arrange them according to categories as in C++/C

**Comment by maltejur** [comment]
@siriak what do you think about those changes?

**Comment by siriak** [comment]
> In C# tests are written separately, DS and Algorithms are also placed separately. In general, each file should have it's own test function and we are supposed to execute those tests in CI to ensure the correctness of implementation. And instead of arranging the algorithms and DS separately, we should arrange them according to categories as in C++/C

1. Putting algorithms and DS together in a single project is no big deal, it's just cleaner to keep them separate IMO.
2. There is a 93% code coverage in the C# repo and everything is well covered with tests.
3. Tests are already running in the CI pipeline.
4. We don't put test code and code under test in the same project in C# because code under test must be in a library or app project, while testing code must be in a unit tests project.
5. Placing code in multiple (>10) separate folders gives us 2 options: either make a project per top-level folder (not viable, will get cyclic references sooner or later) or make a single project (kind of ok, but where to put tests?)

**Comment by maltejur** [comment]
I've reworked the whole process of how the algorithms get fetched for the website (the `DIRECTORY.md`s are now obsolete), that means all the original issues should be fixed now. Do you think it is still a good idea to try to bring all the repositories to a common standard @ayaankhan98?

**Comment by ayaankhan98** [comment]
> I've reworked the whole process of how the algorithms get fetched for the website (the `DIRECTORY.md`s are now obsolete), that means all the original issues should be fixed now. Do you think it is still a good idea to try to bring all the repositories to a common standard @ayaankhan98?

Yes, i think there must be a common standard for all the repositories.
Basically i think there is no need to maintain project type structure in such repositories, because each algorithm is independent of other and also each data structure is independent of other. It would be nice if we sum up one single algorithm in a single file (Implementation + Documentation + Tests). And arrange these files according to their categories. Most of the traffic of these repositories are among those peoples who are completely new to opensource or i would say who are new to computer programming (College undergraduates), our aim is to simplify the learning process by bringing all the generall data structures and algorithims under a single roof of The Algorithms. So, instead of creating a complex project strucutres i think it is better to keep things simple. we are not building any library or framework for algorithms, rather we are just simplifying the learning process.

**Comment by maltejur** [comment]
I've gone ahead and created a new issue for that #64

**Comment by ayaankhan98** [comment]
> I've gone ahead and created a new issue for that #64

Okay, Let's see what other maintainers think.
