### ISSUE TITLE
Bring all the folder structures of the repositories to a common standard

### ISSUE THREAD

**Issue by maltejur** [TheAlgorithms/website#64]
It is probably a good idea to bring all the folders in the different repositories to a common standard.

From @ayaankhan98 https://github.com/TheAlgorithms/website/issues/60#issuecomment-829386192
> Yes, i think there must be a common standard for all the repositories.
Basically i think there is no need to maintain project type structure in such repositories, because each algorithm is independent of other and also each data structure is independent of other. It would be nice if we sum up one single algorithm in a single file (Implementation + Documentation + Tests). And arrange these files according to their categories. Most of the traffic of these repositories are among those peoples who are completely new to opensource or i would say who are new to computer programming (College undergraduates), our aim is to simplify the learning process by bringing all the generall data structures and algorithims under a single roof of The Algorithms. So, instead of creating a complex project strucutres i think it is better to keep things simple. we are not building any library or framework for algorithms, rather we are just simplifying the learning process.

There are already a lot of repositories with the same or almost the same folder structure (python, C++, C, ...), so we are probably going with a folder structure like in the [python repo](https://github.com/TheAlgorithms/Python). 

That means, every algorithm is in a single file (including inline documentation and tests) and every repo has the same top level folders (for example `divide_and_conquer`).

**Comment by siriak** [comment]
I strongly disagree with @ayaankhan98 on this matter because every language has its own style and ways. This is the reason why we need algorithms in many languages instead of just implementing them once in a pseudo-language. Algorithm implementations in different languages are the same algorithm, just expressed differently. This allows folks to learn the way things are done in a language. For example, one class per file rule is a de-facto standard in the .Net world and there is no good reason to violate this and put tests and code together. If we do so, people will get bad coding habits and will have to re-learn and break their bad coding habits when the time to do real work comes. As we are a big community and many people using our repositories are students, I think it's irresponsible from our side to set them a bad example with code that violates language and industry standards and best practices.

**Comment by ayaankhan98** [comment]
some previous discussions on the same issue https://github.com/TheAlgorithms/Java/issues/474

**Comment by ayaankhan98** [comment]
In project type structure files are dependent on each other, learners will not be capable of executing a single file in isolation.

**Comment by siriak** [comment]
> In project type structure files are dependent on each other, learners will not be capable of executing a single file in isolation.

Yes, you cannot execute a file in C# and other compiled languages. And what does it mean to execute an algorithm in the first place? You can apply an algorithm to solve an instance of a problem, but you cannot execute an algorithm per se.
