### ISSUE TITLE
Category strings don't translate on website

### ISSUE THREAD

**Issue by milotype** [TheAlgorithms/website#67]
Category tags don't translate on website, even though the categories are translated at Weblate! Please see attached screenshots.

Also, some categories are not defined at Weblate, for instance:

- Machine Learning
- Neural Network
- maybe others?

![translate01](https://user-images.githubusercontent.com/43657314/117980458-44ddf400-b334-11eb-8832-c322bd9de971.png)

![translate02](https://user-images.githubusercontent.com/43657314/117980469-48717b00-b334-11eb-938f-1bc15b99fa7b.png)

**Comment by maltejur** [comment]
Hmm yes that's a good point. Categories still don't get Translated fully right now, because they are all dynamically generated from the repositories (Except for that one section in your screenshot where they are hard-coded and thus also translated).

I will work on being able to translate all of the categories (and maybe even the algorithm names).
